version: '3.8'

services:
  video-recorder:
    image: selenoid/video-recorder:latest-release
    network_mode: bridge

  chrome_113:
    image: selenoid/chrome:113.0

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/video:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "4", "-video-output-dir", "/opt/selenoid/video" ]

  maven:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - "./reports:/tests/target"
    depends_on:
      - selenoid
    network_mode: host
    command: mvn clean test "${CUCUMBER_OPTIONS}"
